# Generated by Django 5.1.2 on 2024-11-05 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document', models.PositiveIntegerField(unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('serial', models.CharField(max_length=100)),
                ('responsible', models.ForeignKey(db_column='responsible', on_delete=django.db.models.deletion.CASCADE, to='api.professional')),
            ],
        ),
    ]
